# Generated by Django 4.2.14 on 2025-10-17 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='category',
            field=models.CharField(blank=True, choices=[('daily', '일상'), ('work', '업무'), ('personal', '개인')], db_index=True, max_length=20, null=True),
        ),
    ]
