name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Lint
        run: |
          ruff check .
          black --check .
      - name: Run tests
        env:
          DEBUG: true
          SECRET_KEY: test-secret
          ALLOWED_HOSTS: localhost,127.0.0.1
          DATABASE_URL: sqlite:///db.sqlite3
        run: |
          python manage.py migrate --noinput
          python manage.py test -v 2
